# Generated by Django 4.2.16 on 2025-08-24 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaxTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('received', 'Received'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sender_number', models.CharField(max_length=20)),
                ('recipient_number', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('converted_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fax_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaxQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('job_uuid', models.CharField(blank=True, max_length=80, null=True)),
                ('event_name', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='fax.faxtransaction')),
            ],
            options={
                'db_table': 'fax_queue',
                'ordering': ['created_at'],
            },
        ),
    ]
